theme: jekyll-theme-tactile
title: Bruno Peres - User Experience Designer
description: Over 10 years of UX and digital experience. Possess extensive knowledge about technologies, digital trends and best practices.
